### ISSUE TITLE
Where is the output file?

### ISSUE THREAD

**Issue by Reid115** [tarql/tarql#100]
Sorry for such a simple question, but where does the triples output get saved? I can't find any file that gets created when I run the command. I've looked everywhere for an answer to this. Someone asked the same question here, but no one responded:
https://groups.google.com/g/tarql/c/NbC3pbhibSI

Thanks.

**Comment by cygri** [comment]
The output is printed to the standard output (`stdout`). The standard output can be redirected to a file using standard OS commands. The details will depend on your operating system but usually the syntax is something like:
```
tarql [options] > output-file.csv
```
Feel free to reopen if you need further help.

**Comment by Reid115** [comment]
Thanks!
