### ISSUE TITLE
Reusing previous individuals, duplicate triples

### ISSUE THREAD

**Issue by Reid115** [tarql/tarql#101]
I'm curious if it's possible to reference individuals created in previous rows, or remove duplicate triples. For example, say I have a CSV like so:

```
0,child_name,parent_name
0,bill,joe
0,mary,paul
0,mark,joe
```

Each row represents a child with some parent. For some reason tarql completely misses whatever is in the first column, so that's why there's just zeros there. If I remove that column, it won't see ?child_name (is this a bug?). Anyways, say my mapping file looks like this:

```
PREFIX ex:	<http://example.org/>
PREFIX rdfs:	<http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
	?child_uri a ex:Child ;
		rdfs:label	?child_name ;
		ex:has_parent	?parent_uri .

	?parent_uri a ex:Parent ;
		rdfs:label	?parent_name ;
		ex:has_child	?child_uri .
}
WHERE {
	BIND (URI(CONCAT('http://example.org/child-', ?child_name)) AS ?child_uri)
	BIND (URI(CONCAT('http://example.org/parent-', ?parent_name)) AS ?parent_uri)
}
```

The problem is that I only want a new parent to be created if that uri hasn't already been created. This complicates things because, even if that was possible, I would have to specify which specific triples I want to be "one time" triples, and which I want to append. In this case, I only want the rdf:type and rdfs:label triples to be created once for the parent, but I want the ex:has_child triple to be appended each time. The resulting output looks like this:

```
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix ex:  <http://example.org/> .
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

ex:child-bill  rdf:type  ex:Child ;
        rdfs:label     "bill" ;
        ex:has_parent  ex:parent-joe .

ex:parent-joe  rdf:type  ex:Parent ;
        rdfs:label    "joe" ;
        ex:has_child  ex:child-bill .

ex:child-mary  rdf:type  ex:Child ;
        rdfs:label     "mary" ;
        ex:has_parent  ex:parent-paul .

ex:parent-paul  rdf:type  ex:Parent ;
        rdfs:label    "paul" ;
        ex:has_child  ex:child-mary .

ex:child-mark  rdf:type  ex:Child ;
        rdfs:label     "mark" ;
        ex:has_parent  ex:parent-joe .

ex:parent-joe  rdf:type  ex:Parent ;
        rdfs:label    "joe" ;
        ex:has_child  ex:child-mark .
```

As you can see, the parent "joe" is created twice, once for the child "bill" and once for the child "mark". The solution I see for this is to just remove duplicate triples before and regroup, which I feel like wouldn't be that difficult to implement with Jena. It could be a command flag like "--no-duplicates" or something. Any thoughts are appreciated.

**Comment by cygri** [comment]
There is `--dedup` which does what you ask.

Feel free to reopen if needed.

**Comment by Reid115** [comment]
I've tried --dedup and it does nothing. I'm not sure what I'm supposed to put for the window size; I've tried 0, 1, and 2, but nothing changes. I'm also still curious why tarql doesn't parse the first column.

**Comment by cygri** [comment]
The window size is the number of most recent triples that are kept in a buffer to check for duplicates. Try 100000.

I've tried the data sample and query that you gave above. I removed the initial 0 values from every row. It runs fine and parses the `child_name` column.
