### ISSUE TITLE
Unable to use tarql command

### ISSUE THREAD

**Issue by SPARQLTrainee** [tarql/tarql#106]
Hello!

I am still a beginner regarding the handling of SPARQL scripts and using TARQL to process them into trig files as I don't work with it very often (maybe twice a year at maximum)... It is therefore very probable that I am just missing something very obvious.

My problem:
I am not able to use any of the commands shown after bin/tarql.bat is executed. (see screenshot)
![Screenshot 2024-06-05 144013](https://github.com/tarql/tarql/assets/171816792/60fd679e-faf2-4f6a-89da-2a2f505cdf6d)

My environment:
I'm working with Win 11 and I have java installed (I have also checked that PATH and JAVA HOME are set correctly). 
TARQL has been working fine last year on my old device (Win 10 and same installations/settings), however, the device has shown serious perfomance issues lately so I had to change onto the new device. 

Thanks for any help and/or input!

Kind regards,
Alina

**Comment by SPARQLTrainee** [comment]
Ah also: I am using the terminal of Visual Studio Code (i believe it is based on PowerShell?) for entering the commands.

**Comment by SPARQLTrainee** [comment]
After a lot of try and error, I think I was able to execute the command directly out of the bin folder but it gives me an error that I don't understand anymore:
Input:
`PS C:\programming\tarql-1.2\bin> .\tarql C:/programming/researchspace/importobjects/objects2024/objectsoffline.sparql C:/programming/researchspace/importobjects/objects2024/2024objectlisttt217.CSV > C:/programming/researchspace/importobjects/objects2024/objects2024offline.trig`
Output:
`org.apache.jena.iri.impl.IRIImplException: <C:/programming/researchspace/importobjects/objects2024/objectsoffline.sparql> Code: 11/LOWERCASE_PREFERRED in SCHEME: lowercase is preferred in this component
        at org.apache.jena.iri.impl.AbsIRIFactoryImpl.throwAnyErrors(AbsIRIFactoryImpl.java:71)
        at org.apache.jena.iri.impl.AbsIRIFactoryImpl.construct(AbsIRIFactoryImpl.java:55)
        at org.apache.jena.riot.out.NodeFormatterTTL.<init>(NodeFormatterTTL.java:55)
        at org.apache.jena.riot.writer.WriterStreamRDFBase.setFormatter(WriterStreamRDFBase.java:73)
        at org.apache.jena.riot.writer.WriterStreamRDFBase.base(WriterStreamRDFBase.java:125)
        at org.deri.tarql.StreamingRDFWriter.writeTurtle(StreamingRDFWriter.java:71)
        at org.deri.tarql.tarql.exec(tarql.java:217)
        at jena.cmd.CmdMain.mainMethod(CmdMain.java:93)
        at jena.cmd.CmdMain.mainRun(CmdMain.java:58)
        at jena.cmd.CmdMain.mainRun(CmdMain.java:45)
        at org.deri.tarql.tarql.main(tarql.java:57)`
I am working with a SPARQL script I have successfully used in earlier years and I am using it with a new csv file every year. Does the error has something to do with the csv file?

**Comment by cygri** [comment]
Try adding `--base` to your command line:
```
.\tarql --base http://example.com/ ...sparql ...CSV > ...trig
```
If that works, then compare the new output to output from previous runs to figure out a more appropriate base URI.

**Comment by SPARQLTrainee** [comment]
Thanks a lot! This has solved my problem. 

My SPARQL script never had a line BASE `<http://www.example.com>`. Instead, I have formulated the complete URI in my first BIND command:
`BIND(URI(CONCAT("http://localhost:10214/resource/id/object/",?Object_ID)) AS ?object)`
Adding my exact base URI (`http://localhost:10214/`) to the tarql command resulted in cutting out the base part from all constructed triples. I tried to instead add a fictional base URI (`http://example.com/`) and this has worked wonderfully.

I am still trying to figure out, why I can only perfom tarql commands when writing them out of the bin folder `C:\programming\tarql-1.2\bin`. However, creating the trig files was more time pressured and I'm very grateful to you for solving my issue in this regard.

Have a nice day,
Alina

**Comment by cygri** [comment]
It sounds like the PATH variable is not set correctly. The whole path to the Tarql bin directory (C:\programming\tarql-1.2\bin) must be in the PATH environment variable.

I’m not sure if anything special has to be done for VS Code to pick up the variable. Perhaps try typing `echo $PATH` both in the VS Code terminal and in the normal Windows terminal.

**Comment by SPARQLTrainee** [comment]
After a few days, the tarql command works fine again. I think you were right with the path variable even though they were set correctly. I had tried `echo $PATH` from various terminals and it didn't seem to work at all. Now however, it gives the expected response. My computer must have had a little hiccup there.

Thanks a lot for the help!

Best wishes,
Alina
