### ISSUE TITLE
empty output even for examples from homepage

### ISSUE THREAD

**Issue by S6savahd** [tarql/tarql#42]
the output is empty for my CSV files as well as the example  CSV and their queries shown in the homepage. any hint?

**Comment by cygri** [comment]
What version of Tarql are you using? What OS are you on? What examples exactly are you trying?

**Comment by S6savahd** [comment]
I have tarql version 1.0a and I installed it on vm-Ubuntu using vagrant, I am feeding tarql with example 2.

**Comment by S6savahd** [comment]
documentation need to be improved! it needs a lot of effort to get tarql working.

**Comment by akuckartz** [comment]
@S6savahd Can you help improving the documentation?

What was the cause of your problem and how did you solve it?
