### ISSUE TITLE
New options: quote start and stop strings

### ISSUE THREAD

**Issue by akuckartz** [tarql/tarql#43]
`--quotechar` is not enough in some cases. There can be *two different strings* enclosing a quote/text.

**Comment by cygri** [comment]
Examples/evidence?

**Comment by akuckartz** [comment]
Yes, the data I have in front of me contains such string-values between ",":
~~~
<![CDATA[This is string, and this is the rest of the string]]>
~~~

(I would like to convert the data to RDF - and make the result available as Open Data.)

**Comment by cygri** [comment]
So, XML escaping in a CSV file. I'm not in favour of adding extra code to Tarql to support this special kind of idiocy.

If you do a global search and replace of `<![CDATA[` to `"` and `]]>` to `"`, then with luck a normal CSV reader will be able to handle the file.

**Comment by akuckartz** [comment]
> special kind of idiocy creativity. (Apologies for the bad language.)

I do not feel offended: I did not create that idiocity ;-)
