### ISSUE TITLE
Document how to split a cell into multiple values

### ISSUE THREAD

**Issue by cygri** [tarql/tarql#46]
It's not uncommon to have multiple values in a single cell, for example semicolon-separated values within a comma-separated file. Often it is desirable to split these into separate values when transforming to RDF. This is a bit tricky because it means that multiple SPARQL bindings need to be generated from a single input row, and this can't be done with normal SPARQL functions.

The Jena property function `apf:strSplit` addresses this problem, but I'm not 100% sure that property functions work correctly in Tarql. Needs to be tested.

**Comment by cygri** [comment]
Added an example to the index page

**Comment by KonradHoeffner** [comment]
I get the following warning:
```
WARN  Class 'org.apache.jena.sparql.pfunction.library.strSplit' found but not a Function
WARN  URI <http://jena.apache.org/ARQ/property#strSplit> has no registered function factory
```

**Comment by KonradHoeffner** [comment]
Also, cannot BIND as split variable for further processing, as the following returns no triples:

```
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX he: <http://www.snik.eu/ontology/he/>
PREFIX apf: <http://jena.apache.org/ARQ/property#>

CONSTRUCT
{
    ?s he:page ?pd.
}

FROM <file:htest.csv>
WHERE
{
    BIND (uri(concat(tarql:expandPrefix('he'),?SubjektUri)) AS ?s)
    BIND(xsd:positiveInteger(?pdd) as ?pd)                                                                                                                                                                                                    
    ?pdd apf:strSplit (?SeiteDefinition ";")
    filter(BOUND(?SeiteDefinition))
}
```
