### ISSUE TITLE
Issues using ROWNUM for URI in SELECT or CONSTRUCT

### ISSUE THREAD

**Issue by edjaeger** [tarql/tarql#48]
I have a problem binding a ROWNUM to a URI in either a SELECT or CONSTRUCT clause.  Here should be necessary information to reconstruct this.

Start with test.csv -->
id1,id2,id3,fact
1010,12345,a21,109
1010,12346,a21,110
1011,54321,b32,201
1012,76543,c81,301

now start with test1a.sparql -->
PREFIX ex: http://ex.org/a#
SELECT ?ROWNUM ?id1 ?id2 ?id3 ?fact WHERE {}
## run via: tarql  test1a.sparql test1.csv   -->
# | ROWNUM | id1    | id2     | id3   | fact  |

| 1      | "1010" | "12345" | "a21" | "109" |
| 2      | "1010" | "12346" | "a21" | "110" |
| 3      | "1011" | "54321" | "b32" | "201" |
## | 4      | "1012" | "76543" | "c81" | "301" |

Second try test1c.sparql -->
PREFIX ex: http://ex.org/a#
SELECT ?ROWNUM ?id1 ?id2 ?id3 ?fact ?rowindex
WHERE {
  BIND (URI(CONCAT('http://ex.org/index/', ?ROWNUM)) AS ?rowindex)
}

Run via -->  tarql  test1c.sparql test1.csv
## Produces -->
# | ROWNUM | id1    | id2     | id3   | fact  | rowindex |

| 1      | "1010" | "12345" | "a21" | "109" |          |
| 2      | "1010" | "12346" | "a21" | "110" |          |
| 3      | "1011" | "54321" | "b32" | "201" |          |
## | 4      | "1012" | "76543" | "c81" | "301" |          |

Note that rowindex does not produce any output.

Now try in a CONSTRUCT clause
try test1d.sparql -->
PREFIX ex: http://ex.org/a#

CONSTRUCT {
  ?ROWNUM a ex:entry;
   ex:prop1 ?id1; 
}
WHERE {
  BIND (URI(CONCAT('http://ex.org/index/', ?ROWNUM)) AS ?rowindex)
}

Run via --> tarql  test1d.sparql test1.csv
Produces --> NO OUTPUT!

Let's make another attempt.  test1e.sparql -->
PREFIX ex: http://ex.org/a#

CONSTRUCT {
  ?rowindex a ex:entry;
   ex:prop1 ?id1; 
}
WHERE {
  BIND (URI(CONCAT('http://ex.org/index/', ?ROWNUM)) AS ?rowindex)
}

Run via --> tarql  test1e.sparql test1.csv
Produces --> NO OUTPUT

**Comment by PreVaDu** [comment]
I have to confirm this bug with different data.

**Comment by cygri** [comment]
`CONCAT` in SPARQL only works for string arguments. `?ROWNUM` is numeric. It needs to be used as `STR(?ROWNUM)` in `CONCAT`.
