### ISSUE TITLE
how to expand prefixed URIs?

### ISSUE THREAD

**Issue by VladimirAlexiev** [tarql/tarql#49]
http://stackoverflow.com/questions/41168241/how-to-convert-string-to-url-with-arq-tarql

Column `prop` has strings like `dc:source`, `skos:broader` etc. How can I convert these to the corresponding URLs? Assume I have all needed prefixes defined in the `tarql` query.

I can do this statically eg `uri(concat(str(dc:),"source"))` but how to do it dynamically? The problem can be narrowed to this: given a prefix `dc:` how to expand it to the appropriate URL?

Looked at [ARQ functions](https://jena.apache.org/documentation/query/library-function.html) but didn't find anything appropriate. If there's no other solution, I can use a VALUES table that repeats the prefixes and namespaces, but what an ugly solution...

**Comment by cygri** [comment]
Until now there was no way of doing this, but I've just added `tarql:expandPrefix(?prefix)` and `tarql:expandPrefixedName(?qname)`. The former turns `dc` into the corresponding namespace IRI (as a string), the latter turns `dc:title` into the corresponding expanded IRI (as a IRI). The `tarql` namespace doesn't need to be declared.

**Comment by VladimirAlexiev** [comment]
excellent!
