### ISSUE TITLE
can't run on large file with complex query

### ISSUE THREAD

**Issue by VladimirAlexiev** [tarql/tarql#50]
I'm running tarql on a 3.4Gb file with 4,000,001 rows. My query is 420 lines.
java's eaten 2Gb RAM and stays at 90-95% CPU, for half an hour now.
There is no output yet.
The same query is tested sucessfully with 33k rows.

Questions:
1. Does tarql try to slurp the whole input file?
2. Does it try to build RDF model in memory

If so, that's IMHO a very bad architectural decision. There's no flow of info from row to row (except `?ROWNUM`), so it can process and output one row at a time. There's no reason to eat 2Gb if each row is under 2-3k.

Of course I can split the file to 100 chunks but... Maybe I better turn to r2rml+sql.

**Comment by VladimirAlexiev** [comment]
Ran out of memory after 30-40 min. I think this is while still reading the input (1 above):
```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at com.hp.hpl.jena.graph.impl.LiteralLabelFactory.create(LiteralLabelFactory.java:87)
        at com.hp.hpl.jena.graph.NodeFactory.createLiteral(NodeFactory.java:66)
        at com.hp.hpl.jena.graph.NodeFactory.createLiteral(NodeFactory.java:55)
        at org.deri.tarql.CSVParser.toBinding(CSVParser.java:104)
        at org.deri.tarql.CSVParser.next(CSVParser.java:150)
        at org.deri.tarql.CSVParser.next(CSVParser.java:26)
        at org.deri.tarql.CSVTable$2.next(CSVTable.java:77)
        at org.deri.tarql.CSVTable$2.next(CSVTable.java:65)
        at com.hp.hpl.jena.sparql.engine.iterator.QueryIterPlainWrapper.moveToNextBinding(QueryIterPlainWrapper.java:57)

        at com.hp.hpl.jena.sparql.engine.iterator.QueryIteratorBase.nextBinding(QueryIteratorBase.java:154)
        at com.hp.hpl.jena.sparql.algebra.table.TableN.materialize(TableN.java:53)
        at com.hp.hpl.jena.sparql.algebra.table.TableN.<init>(TableN.java:43)
        at com.hp.hpl.jena.sparql.algebra.TableFactory.create(TableFactory.java:54)
        at com.hp.hpl.jena.sparql.engine.main.iterator.QueryIterJoinBase.calc(QueryIterJoinBase.java:51)
        at com.hp.hpl.jena.sparql.engine.main.iterator.QueryIterJoinBase.<init>(QueryIterJoinBase.java:47)
        at com.hp.hpl.jena.sparql.engine.main.iterator.QueryIterJoin.<init>(QueryIterJoin.java:30)
        at com.hp.hpl.jena.sparql.engine.main.OpExecutor.execute(OpExecutor.java:337)
        at com.hp.hpl.jena.sparql.engine.main.ExecutionDispatch.visit(ExecutionDispatch.java:220)
        at com.hp.hpl.jena.sparql.algebra.op.OpTable.visit(OpTable.java:58)
        at com.hp.hpl.jena.sparql.engine.main.ExecutionDispatch.exec(ExecutionDispatch.java:47)
        at com.hp.hpl.jena.sparql.engine.main.OpExecutor.exec(OpExecutor.java:123)
        at com.hp.hpl.jena.sparql.engine.main.OpExecutor.execute(OpExecutor.java:237)
        at com.hp.hpl.jena.sparql.engine.main.ExecutionDispatch.visit(ExecutionDispatch.java:131)
        at com.hp.hpl.jena.sparql.algebra.op.OpSequence.visit(OpSequence.java:75)
        at com.hp.hpl.jena.sparql.engine.main.ExecutionDispatch.exec(ExecutionDispatch.java:47)
        at com.hp.hpl.jena.sparql.engine.main.OpExecutor.exec(OpExecutor.java:123)
        at com.hp.hpl.jena.sparql.engine.main.OpExecutor.execute(OpExecutor.java:441)
        at com.hp.hpl.jena.sparql.engine.main.ExecutionDispatch.visit(ExecutionDispatch.java:300)
        at com.hp.hpl.jena.sparql.algebra.op.OpExtend.visit(OpExtend.java:100)
        at com.hp.hpl.jena.sparql.engine.main.ExecutionDispatch.exec(ExecutionDispatch.java:47)
        at com.hp.hpl.jena.sparql.engine.main.OpExecutor.exec(OpExecutor.java:123)
        at com.hp.hpl.jena.sparql.engine.main.OpExecutor.execute(OpExecutor.java:94)
```

So tarql can be used only on small toy examples?

**Comment by cygri** [comment]
Vladimir, Tarql is supposed to stream, and I've used it on files that were larger than the available VM memory. I cannot say why it's not working in your case.

I tend to use `--ntriples` but that might just be superstition.

Does a trivial mapping work on the same input?

You can also just give it more memory by setting `$JAVA_OPTS` to something like `-Xmx8G`. You're not trying to run this on your phone are you? ;-)

**Comment by VladimirAlexiev** [comment]
1. I downloaded a binary from http://lab.linkeddata.deri.ie/2013/tarql/tarql-1.0a-bin.zip. Is there a newer version? Should I build from source?
2. a select * or even select one col doesn't stream rows. I think the reason is that it wants to compute the col width for output
3. a trivial construct (all fields emitted against one node) streams rows, even if it has all 151 cols
4. my construct has about 100 binds, makes about 25 (connected) nodes and dispatches about 130 values among these nodes

But the same construct is tested successfully with 20-33k rows.
For 20k rows, there is a 5s delay, it eats 1Gb RAM, then starts streaming rows.

WEIRD. Smells like a memory leak?

**Comment by cygri** [comment]
The version you found is outdated and indeed doesn't stream (and the charge of only working with toy examples is somewhat justified).

Yes, please build from source. Sorry for the lack of an official binary release.

**Comment by VladimirAlexiev** [comment]
Thanks! We'll try that right away.

**Comment by pandid** [comment]
We build it and we experience similar behaviour. The line bellow seems to read the whole csv file prior to writing any triple. Then how the model is created?
https://github.com/tarql/tarql/blob/master/src/main/java/org/deri/tarql/CSVParser.java#L187

Our expectation was that you will build an RDF model per line and write that into triples. Note that we don't have references between lines. What writing in streams means?
thanks!

**Comment by cygri** [comment]
@pandid The line you're pointing to just skips empty lines at the beginning of the file. It doesn't read in the whole file.

What version are you using?

**Comment by pandid** [comment]
Apologies. I might have digging deeper into the code. 
Anyway, I have build it from source, and I see it running for few hours, runs some threads but I see my ttl file still empty.
I've tried to force jstack and see what is going on. Here is part of the stack...

Thread 29398: (state = IN_JAVA)
 - au.com.bytecode.opencsv.CSVParser.parseLine(java.lang.String, boolean) @bci=422, line=213 (Compiled frame; information may be imprecise)
 - au.com.bytecode.opencsv.CSVParser.parseLineMulti(java.lang.String) @bci=3, line=174 (Compiled frame)
 - au.com.bytecode.opencsv.CSVReader.readNext() @bci=21, line=237 (Compiled frame)
 - org.deri.tarql.CSVParser.next() @bci=14, line=146 (Interpreted frame)
 - org.deri.tarql.CSVParser.next() @bci=1, line=26 (Interpreted frame)
 - org.deri.tarql.CSVTable$2.next() @bci=14, line=77 (Interpreted frame)
 - org.deri.tarql.CSVTable$2.next() @bci=1, line=65 (Interpreted frame)
 - com.hp.hpl.jena.sparql.engine.iterator.QueryIterPlainWrapper.moveToNextBinding() @bci=4, line=57 (Interpreted frame)
 - com.hp.hpl.jena.sparql.engine.iterator.QueryIteratorBase.nextBinding() @bci=67, line=154 (Interpreted frame)

**Comment by cygri** [comment]
Okay, thanks for checking. Does a trivial mapping (empty `WHERE` clause) work on the same input?

**Comment by pandid** [comment]
Ok thanks for the hint. I also have tried to debug the code. The code repeatedly calls CSVParser method next for quite a while. Is it parsing the csv there? I've seen next() have been called on each line?

I've also run the code with trivial mapping, still waiting for the result. It keeps calling on the same method 
        at org.deri.tarql.CSVParser.next(CSVParser.java:146)
I will keep you posted how it goes tomorrow as it still runs.
thanks for your help!

**Comment by pandid** [comment]
OK so with empty where clause it runs over night and still haven't finished. The jstack shows it still reads lines under next in CSVParser. I've run it with 30g and this is the current memory state:

Heap
 PSYoungGen      total 10485248K, used 9173312K [0x0000000580000000, 0x0000000800000000, 0x0000000800000000)
  eden space 10484736K, 87% used [0x0000000580000000,0x00000007afe382b0,0x00000007fff00000)
  from space 512K, 18% used [0x00000007fff80000,0x00000007fff98000,0x0000000800000000)
  to   space 512K, 0% used [0x00000007fff00000,0x00000007fff00000,0x00000007fff80000)
 ParOldGen       total 9979392K, used 4400921K [0x0000000080000000, 0x00000002e1180000, 0x0000000580000000)
  object space 9979392K, 44% used [0x0000000080000000,0x000000018c9c6700,0x00000002e1180000)
 Metaspace       used 11960K, capacity 12010K, committed 12160K, reserved 1060864K
  class space    used 1599K, capacity 1617K, committed 1664K, reserved 1048576K

waiting for some next steps. I will run it with more memory while I'll wait for your input.

**Comment by cygri** [comment]
Just to confirm: It has been running overnight without starting to generate any output? And this is with `--ntriples`?

**Comment by pandid** [comment]
no output. No _--ntriples_ as well.

**Comment by pandid** [comment]
this is how I run it:
tarql  -t ../config/link1.tarql unix.tdv > unix.ttl

**Comment by VladimirAlexiev** [comment]
Hi @cygri! 
There are a bunch of values that I need to make conditional, eg 1. ignore fields of all zeros, 2. emit /address/physical URL only if some fields for the physical address are present... About half of the 100 binds are conditional
```sparql
  # Ignore value 000 in county_code, state_prov_code, country_code, continent_code
  bind(if(regex(?phy_city_code      ,"^0+$"),?undef,uri(concat(str(dnb:),"country/",?phy_country_code,"/city/",     ?phy_city_code      ))) as ?phyCityUrl)
  bind(if(regex(?phy_county_code    ,"^0+$"),?undef,uri(concat(str(dnb:),"country/",?phy_country_code,"/county/",   ?phy_county_code    ))) as ?phyCountyUrl)
  bind(if(regex(?phy_state_prov_code,"^0+$"),?undef,uri(concat(str(dnb:),"country/",?phy_country_code,"/stateProv/",?phy_state_prov_code))) as ?phyStateProvUrl)
  bind(if(regex(?phy_country_code   ,"^0+$"),?undef,uri(concat(str(dnb:),                             "country/",   ?phy_country_code   ))) as ?phyCountryUrl)
  bind(if(regex(?phy_continent_code ,"^0+$"),?undef,uri(concat(str(dnb:),                             "continent/", ?phy_continent_code ))) as ?phyContinentUrl)
  bind(coalesce(?phy_addr1, ?phy_addr2, ?phy_postal_code, ?phyCityUrl, ?phycountyUrl, ?phyStateProvUrl, ?phyCountryUrl,  ?phyContinentUrl) as ?hasPhyAddr)
  bind(if(bound(?hasPhyAddr),uri(concat(str(?companyUrl),"/address/physical")),?undef) as ?phyAddrUrl)
  bind(if(?available_address_phy="Y",true,if(?available_address_phy="N",false,?undef)) as ?available_address_PHY)
```
I use a "variable" `?undef` because SPARQL allows the constant UNDEF to be used in only one place:
```sparql
  values ?undef {undef}
```
It is this single line (the first thing in WHERE) that fucks up everything. 

Replacing it with this:
```sparql
  bind(1+"undef" as ?undef)
```
fixes the problem.

So we have a workaround, but I think I found a bug in ARQ. Can you help me formulate it?

**Comment by VladimirAlexiev** [comment]
Wrote too soon. 
- the tdv input is 3.4Gb (4M rows)
- we expect the ttl output to be about 26Gb
- but after outputting 1.05G, it gets stuck (stops outputting). This is exactly 1,132,167,168 bytes: we tried on Windows and Ubuntu with different Java, it stops at the same place.
- On Windows, the process consumes 25-30% CPU and 2.2Gb RAM (slowly growing).
- the last few lines of Turtle are:
```turtle
<http://data.ontotext.com/resource/dnb/country/805/city/007554>
        rdf:type                  dnbo:City ;
        fibo-fnd-rel-rel:hasUniqueIdentifier  "007554" ;
        fibo-fnd-rel-rel:hasName  "Scottsdale" ;
        dnbo:hasCounty            <http://data.ontotext.com/resource/dnb/country/805/county/467> ;
        dnbo:hasStateProv         <http://data.ontotext.com/resource/dnb/country/805/stateProv/005> ;
        dnbo:hasCountry           <http://data.ontotext.com/resource/dnb/country/805> .

<http://data.ontotext.com/resource/dnb/country/805/county/467>
        rdf:type                  dnbo:County ;
```
- There's nothing strange about the data for this county. It has been output before (there is redundancy in the data):
```turtle
<http://data.ontotext.com/resource/dnb/country/805/county/467>
        rdf:type                  dnbo:County ;
        fibo-fnd-rel-rel:hasUniqueIdentifier  "467" ;
        fibo-fnd-rel-rel:hasName  "Maricopa" ;
        dnbo:hasStateProv         <http://data.ontotext.com/resource/dnb/country/805/stateProv/005> ;
        dnbo:hasCountry           <http://data.ontotext.com/resource/dnb/country/805> .
```
- (after killing the process, it appended "fTerminate batch job (Y/N)?", for a total of 1,132,167,197 bytes)
- it gets stuck at row 173394 of 4000001 (4.3%)
```sh
> grep -n 00011023889 link_jun2014_f1.tdv
173394:00011023889      N       N       N       Banana Republic, LLC    Banana Republic N       7014 E Camelback RdScottsdale   Maricopa        Arizona USA...
```

**Comment by cygri** [comment]
Try `--ntriples`. No idea whether that will make a difference, but it would narrow down where the problem is.

ARQ doesn't seem to optimise `VALUES` very well. The way you use it, it should just add a new variable with unbound value to each row. Instead, ARQ seems to execute it by doing a join between a one-row table and a 4M-row table, and the join implementation forces a slurp of the entire file into memory.

The ARQ version we use is pretty old, so this may well be fixed in more recent versions. But Tarql uses internal ARQ APIs that have changed since, so upgrading isn't trivial.

We could add a pre-provided variable `?null` or `?unbound` or `?undef` to address your use case.

The hang after 1,132,167,168 bytes is interesting. It's divisible by 2^15, so the number is probably not random. It is also just above 50% of the maximum length of a String in Java. So maybe it's keeping the entire String somewhere in a buffer, and the buffer auto-grows by doubling in size when it's full, and it gets stuck when trying to grow the buffer beyond the maximum size supported by Java? The Windows memory usage numbers lend support to that theory—a string of that many bytes would take around 2.1G of memory. Anyway, it seems that the sticking point is writing the output, and not reading the input, and also not total available memory.

Hence the question about `--ntriples`. It uses a different code path for the output. If that doesn't work, then probably a deep dive into the Jena output classes used from `StreamingRDFWriter.java` is needed.

**Comment by pandid** [comment]
Unfortunately   using the _--ntriples_  options leads to the same outcome. It hangs after 2.6 gb.

**Comment by VladimirAlexiev** [comment]
- should we post a bug against ARQ VALUES?
- ` bind(1+"undef" as ?undef)` makes such a variable
- your buffer auto-growth theory is interesting. But it does spit out triples in a streaming fashion, so why would it need to grow the buffer so many times?
- I also think it hangs on output not input. But how about the stack trace above: doesn't it indicate `parseLine(CSVParser.java:213)`? Or it's not actually stuck at that place...
- Splitting to chunks of 100001 rows is a workable workaround for us. Cheers!

**Comment by cygri** [comment]
I don't see evidence of a *bug* in ARQ. There is a a *possible lack of optimisation*. Tarql is an atypical use of ARQ, and the response could just be that it was not designed for situations involving 4M rows. And as I said, it's an old version of ARQ and an effort should be made to check if the problem is still there in the current version.

The fact that `--ntriples` outputs significantly more data but then also hangs speaks against the theory of a problem in the output pipeline. (Did it hang at the same input row?)

I looked at the `CSVParser.java` sources earlier and couldn't see any smoking gun. No I/O is performed there, just some string munging. The only potential problem I can see there would be a runaway quote in the input. That is, an opening quote that is never closed, leading to the rest of the file being mistreated as the contents of the same cell. I thought this theory didn't fit some of the evidence you gave earlier.

Could you have a look in the input file for suspicious unmatched quotes in the lines surrounding the last successful one?

**Comment by VladimirAlexiev** [comment]
The first quote is at row 1181 (id 00001095236) and involves these names:  `Toys "r" Us, Inc.` and `Toys "R" Us`. It is correctly converted to:
```turtle
        fibo-fnd-rel-rel:hasLegalName  "Toys \"r\" Us, Inc." ;
        fibo-fnd-rel-rel:hasAlias      "Toys \"R\" Us" ;
```
There are no tabs in the file: this returns nothing:
```sh
grep -an $'\t' link*.txt
```

**Comment by cygri** [comment]
@VladimirAlexiev I have investigated further and now believe that you have a stray unclosed double quote somewhere in your input file. I have tested that case on a large file, and the result is consistent with what you have observed: It stops producing output, and slows to a crawl (down to a handful of lines read per second). This is due to inefficient handling of multi-line values in the CSV parser we use (OpenCSV).

Look for a value containing just an opening double quote and no matching closing double quote, like `Toys "R Us, Inc.`, somewhere shortly after line 173394.

**Comment by VladimirAlexiev** [comment]
You're exactly right!
```sh
perl -ne '@matches = m{(")}g; $matches=@matches; print "$matches quotes, line $.: $_" if $matches%2' link*.txt
1 quotes, line 173397: 00011024150NNNGone Troppo Inc    Emack & Bolio"s ...
```
What threw me off is that balanced quotes (as in `Toys "r" Us`) are handled as literal chars.

So what should I do now, quote it as `\"` ?

**Comment by cygri** [comment]
Yes, OpenCSV's handling of quotes in the middle of content is somewhat questionable. But then, CSV is a rather rubbish and underspecified format with many different variations, so it is very hard to say what the correct behaviour would be.

The standard way of escaping quotes in CSV is by doubling them: `Emack & Bolio""s`. I think this works in OpenCSV.

I've submitted a patch to OpenCSV that would throw a reasonably helpful exception in this case:

https://sourceforge.net/p/opencsv/patches/54/

**Comment by VladimirAlexiev** [comment]
Thanks for your help!
Using double quote fixes the issue.
(but I think I'll convert to single apostrophe in this case).

**Comment by cygri** [comment]
If your file doesn't make use of quotes around fields, you can also set `--quotechar` to some character that never occurs in the file (e.g., a funny Unicode character) to disable quote processing.

**Comment by VladimirAlexiev** [comment]
For the record: both of these are unnecessary:
```sparql
 bind(1+"undef" as ?undef)
 values ?undef {UNDEF}
```
Just use the var `?undef` without binding it: it has the value `UNDEF`.
