### ISSUE TITLE
mvn package appassembler:assemble FAILURE

### ISSUE THREAD

**Issue by pumba-lt** [tarql/tarql#56]
When running `mvn package appassembler:assemble`, I get:

    [ERROR] Failed to execute goal on project tarql: Could not resolve dependencies for project org.deri.tarql:tarql:jar:1.1: Could not find artifact com.opencsv:opencsv:jar:3.9-cygri in central (http://repo.maven.apache.org/maven2) -> [Help 1]

**Comment by cygri** [comment]
See here: https://github.com/tarql/tarql/blob/master/pom.xml#L49

Not much I can do to improve this until the OpenCSV folks deal with this: https://sourceforge.net/p/opencsv/patches/54/

**Comment by DarkLinkXXXX** [comment]
I had to search the issues to find this. Maybe put a note in the README?
