### ISSUE TITLE
[proposal] Embedding base url to output turtle file

### ISSUE THREAD

**Issue by a-andreyev** [tarql/tarql#58]
Hello! Thank you for the project!

Am I right that base url passed from `--base=` cli argument is not adding base prefix to output turtle file?
I guess it would be handy.

For now I'm adding it manually with `sed`:

```
sed -i '1s/^/@base <http:\/\/my_base_url\/> \.\n/' ./somefile.ttl
```

**Comment by cygri** [comment]
I've added a `--write-base` flag. If the flag is present, and Turtle output is used, the base IRI (taken from `--base` on the command line, or from `BASE` in the mapping) will be written to the output file.

Commit: e04b9cba
