### ISSUE TITLE
Replace illegal characters in header

### ISSUE THREAD

**Issue by jaw111** [tarql/tarql#62]
I have a CSV file that has a few characters in the header row (`%`, `(` and `)`) that are not legal characters for variable names in SPARQL 1.1 Query Language.

Would be nice if those were substituted (or ignored) when mapping column names to variable names.

**Comment by cygri** [comment]
There's already a FIXME in the code for this:
https://github.com/tarql/tarql/blob/master/src/main/java/org/deri/tarql/CSVParser.java#L82

Probably just replace them with underscores, like other unsupported characters.

Appropriate test cases should be added around here:
https://github.com/tarql/tarql/blob/master/src/test/java/org/deri/tarql/CSVParserTest.java#L91

**Comment by cygri** [comment]
Production for SPARQL variable names:
https://www.w3.org/TR/sparql11-query/#rVARNAME

**Comment by cygri** [comment]
I'll leave this ticket open, as there are still many (hopefully less frequently occurring) characters that are not correctly handled.

**Comment by cygri** [comment]
Fixed via @patzomir's PR
