### ISSUE TITLE
Artifact com.opencsv:opencsv:jar:3.9-cygri missing when building

### ISSUE THREAD

**Issue by ColinMaudry** [tarql/tarql#71]
Hi,

I just cloned the repo and tried building Tarql with the command below, but I got the following error:

```bash
mvn package appassembler:assemble
```

> Failed to execute goal on project tarql: Could not resolve dependencies for project org.deri.tarql:tarql:jar:1.2-SNAPSHOT: Could not find artifact com.opencsv:opencsv:jar:3.9-cygri in central (https://repo.maven.apache.org/maven2)

**Comment by cygri** [comment]
See here: https://github.com/tarql/tarql/blob/master/pom.xml#L49

I believe that OpenCSV 4.0 which has since been released also includes a fix for this, so just changing the version from `3.9-cygri` to `4.0` might also work, but I have not tried that myself yet.
