### ISSUE TITLE
Memory requirements?

### ISSUE THREAD

**Issue by freundt** [tarql/tarql#75]
Hello,
first of all, thanks for this tool, and the concept behind it: Using SPARQL as a template language for the transformation.

Now, I was wondering what the actual memory overhead is.  I tried the tool with a rather tiny 190 MB file.  The good news is that memory seems to be linear in input file size, the bad news is the factor is something like 10 or 11, i.e. running my file amounts to using about 2 GB of RAM, a portion twice as big takes 4.5 GB.

Not really an issue as such but maybe a request that this could be improved?  Ideally, I'd like to see a streaming approach where memory consumption is independent of input file size.  Only then `--stdin` would really make sense.

**Comment by cygri** [comment]
It depends. In general, Tarql should stream the processing and use constant memory, but there are a number of things that can prevent that from working, so it depends on the query used for the mapping as well as on the command line options. For example, `GROUP BY` would force the entire result into memory. The specific conditions are unfortunately neither documented nor fully understood—Tarql is a fairly thin wrapper around Jena’s ARQ query engine, and ARQ sometimes does surprising things.

Also, how did you measure the required memory? Did you define any the JVM memory settings in the tarql script? The JVM tends to gobble up all available memory up to its configured maximum before it starts garbage collection, so it may temporarily use much more memory than it actually needs. Try giving it a maximum smaller than your input file.

(I realise the documentation really needs improvement around these issues. Ask if anything is unclear.)
