### ISSUE TITLE
An how two with all the steps

### ISSUE THREAD

**Issue by aborruso** [tarql/tarql#79]
Hi,
how to install tarql?

Is this the way

```
git clone https://github.com/cygri/tarql
cd /tarql
mvn clean install -DskipTests
```

Thank you

**Comment by cygri** [comment]
Download from <https://github.com/tarql/tarql/releases>; get the `.tar.gz` version if on Linux or macOS, or the `.zip` for Windows. Uncompress into a location of your choice. Run `bin/tarql`.

**Comment by cygri** [comment]
(Maven is a build tool, not an installation/package manager tool. No need to do anything with Maven unless you want to build from source. In that case it would be `mvn package` which produces the `.tar.gz` and `.zip` distribution files.

**Comment by aborruso** [comment]
thank you @cygri 

I have seen it, and the way you have written is simpler

![image](https://user-images.githubusercontent.com/30607/58631347-98d7a580-82e2-11e9-84d8-a1ed0f6331ac.png)

**Comment by cygri** [comment]
@aborruso Thanks for pointing that out. This text indeed assumes that Tarql has been built from source. I’ll consider changing that in the next documentation update.
