### ISSUE TITLE
apf:strSplit only works before BIND, not afterwards

### ISSUE THREAD

**Issue by KonradHoeffner** [tarql/tarql#82]
Is that intended? I thought SPARQL doesn't care in which order my triples patterns are.

**Generates triples**

    ?supe apf:strSplit (?super ";")
    BIND (URI(CONCAT(tarql:expandPrefix('hito'),?supe)) AS ?sup)

**Generates no triples**

    BIND (URI(CONCAT(tarql:expandPrefix('hito'),?supe)) AS ?sup)
    ?supe apf:strSplit (?super ";")

**Comment by cygri** [comment]
`BIND` is not a triple pattern. The order of `BIND`, `OPTIONAL` and `MINUS` matters in SPARQL.
